### ISSUE TITLE
Cannot configure Phpstan with the DDEV container.

### ISSUE THREAD

**Issue by zaifastafa** [ddev/ddev-contrib#226]
Hi, I keep getting the following error; 

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "docker-compose" (in directory "/home/huzaifa/code/shopware/.ddev"): error=2, No such file or directory
```

Can you provide a guide or a setting configuration how I can run this? @rfay

**Comment by rfay** [comment]
This isn't the right place for this issue, but what you would want to do is configure the location of docker-compose in Build, Execution, Deployment -> Docker -> Tools - and it should be set to ~/.ddev/bin/docker-compose (or expand the `~`, for example /Users/rfay/.ddev/bin/docker-compose or /home/rfay/.ddev/bin/docker-compose
