### ISSUE TITLE
Portainer add-on is causing connections to the wrong database

### ISSUE THREAD

**Issue by adrian-cid** [ddev/ddev-contrib#230]
When I start more than one project the databases start to being mixed between them. I tried to solutions in https://github.com/ddev/ddev/issues/3369 but any of them are working.

ddev version v1.22.0
Docker Compose version 2.20.2

The full descriptions and solution can be found at https://github.com/ddev/ddev/issues/5217

**Comment by rfay** [comment]
BTW, I don't know what DDEV version you were coming from, but I don't believe this had anything to do with v1.22.0. Networks were handled the same way for at least a year or a year and a half. 
Thanks for the PR!

I hope you'll consider creating a Portainer add-on, it's super easy, https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#creating-an-additional-service-for-ddev-get

**Comment by adrian-cid** [comment]
I started reading about the addons, I hope I can do it soon, thanks again
