### ISSUE TITLE
PHP GRPC - installation too slow

### ISSUE THREAD

**Issue by gauravmanerkar** [ddev/ddev-contrib#241]
GRPC installation is too slow. Can it be optimised somehow?

Dockerfile: https://github.com/ddev/ddev-contrib/blob/master/web-container-dockerfiles/grpc/Dockerfile

**Comment by gauravmanerkar** [comment]
@stasadev 
Instead of `pecl` can we use some other alternaive?

**Comment by stasadev** [comment]
The only alternative at this point is to build from source.

https://github.com/grpc/grpc/tree/1751f1043ed00cb064907bf6943c7fcad72516af/src/php#install-the-grpc-extension

**Comment by rfay** [comment]
But of course building from source will be much slower and also requires other packages to succeed. So you're probably stuck with the pecl approach.

**Comment by rfay** [comment]
I was experimenting with this as an addition to docs. The `pecl install` does in fact do the compile from scratch, and of course the approach here does the full build on the first `ddev start`. I found it to be atrocious how much had to be compiled, gave up on it. And I was running it in highly performance, great internet-access gitpod instance.

**Comment by cmuench** [comment]
@rfay @gauravmanerkar Due to the fact that ddev now uses the sury packages, we can install the GRPC module via apt.
Just successfully tested with PHP 8.2 and `ddev config --webimage-extra-packages="php8.2-grpc"`.
So we can simplify the setup here.
